############################################
# Generated environment backend configuration
############################################

resource "local_file" "backend_config" {
  # This file is generated by bootstrap after the state bucket exists. It is
  # intentionally not committed because backend bucket names can differ across
  # accounts and bootstrap runs.
  filename = "${path.module}/../../envs/${var.environment}/backend.tf"

  content = <<EOT
terraform {
  backend "s3" {
    bucket       = "${aws_s3_bucket.terraform_state.id}"
    key          = "${local.tf_backend_key}"
    region       = "${var.aws_region}"
    encrypt      = true
    use_lockfile = true
  }
}
EOT
}
